CANDIDATES = [
 (u'CML 2001', u'acidification potential', u'average European'),
 (u'CML 2001', u'climate change', u'GWP 100a'),
 # (u'CML 2001', u'climate change', u'GWP 20a'),
 # (u'CML 2001', u'climate change', u'GWP 500a'),
 # (u'CML 2001', u'climate change', u'lower limit of net GWP'),
 # (u'CML 2001', u'climate change', u'upper limit of net GWP'),
 (u'CML 2001', u'eutrophication potential', u'average European'),
 # (u'CML 2001', u'eutrophication potential', u'generic'),
 (u'CML 2001', u'freshwater aquatic ecotoxicity', u'FAETP 100a'),
 # (u'CML 2001', u'freshwater aquatic ecotoxicity', u'FAETP 20a'),
 # (u'CML 2001', u'freshwater aquatic ecotoxicity', u'FAETP 500a'),
 # (u'CML 2001', u'freshwater aquatic ecotoxicity', u'FAETP infinite'),
 (u'CML 2001', u'human toxicity', u'HTP 100a'),
 # (u'CML 2001', u'human toxicity', u'HTP 20a'),
 # (u'CML 2001', u'human toxicity', u'HTP 500a'),
 # (u'CML 2001', u'human toxicity', u'HTP infinite'),
 (u'CML 2001', u'land use', u'competition'),
 (u'CML 2001', u'marine aquatic ecotoxicity', u'MAETP infinite'),
 (u'CML 2001', u'resources', u'depletion of abiotic resources'),
 # (u'CML 2001', u'stratospheric ozone depletion', u'ODP 10a'),
 # (u'CML 2001', u'stratospheric ozone depletion', u'ODP 15a'),
 # (u'CML 2001', u'stratospheric ozone depletion', u'ODP 20a'),
 (u'CML 2001', u'stratospheric ozone depletion', u'ODP 25a'),
 # (u'CML 2001', u'stratospheric ozone depletion', u'ODP 30a'),
 # (u'CML 2001', u'stratospheric ozone depletion', u'ODP 40a'),
 # (u'CML 2001', u'stratospheric ozone depletion', u'ODP 5a'),
 # (u'CML 2001', u'stratospheric ozone depletion', u'ODP steady state'),
 (u'EDIP2003', u'ecotoxicity', u'in sewage treatment plants'),
 # (u'EDIP2003', u'eutrophication', u'separate P potential'),
 (u'EDIP2003', u'eutrophication', u'terrestrial eutrophication'),
 # Add these together
 (u'EDIP2003', u'land filling', u'bulk waste'),
 (u'EDIP2003', u'land filling', u'hazardous waste'),
 (u'EDIP2003', u'land filling', u'radioactive waste'),
 (u'EDIP2003', u'land filling', u'slag and ashes'),
 # Excluded because unit is kilograms of mass - can't add together
 # Should be covered by other minderal extraction methods
 # (u'EDIP2003', u'non-renewable resources', u'aluminium'),
 # (u'EDIP2003', u'non-renewable resources', u'antimony'),
 # (u'EDIP2003', u'non-renewable resources', u'brown coal'),
 # (u'EDIP2003', u'non-renewable resources', u'cadmium'),
 # (u'EDIP2003', u'non-renewable resources', u'cerium'),
 # (u'EDIP2003', u'non-renewable resources', u'coal'),
 # (u'EDIP2003', u'non-renewable resources', u'cobalt'),
 # (u'EDIP2003', u'non-renewable resources', u'copper'),
 # (u'EDIP2003', u'non-renewable resources', u'gold'),
 # (u'EDIP2003', u'non-renewable resources', u'iron'),
 # (u'EDIP2003', u'non-renewable resources', u'lanthanum'),
 # (u'EDIP2003', u'non-renewable resources', u'lead'),
 # (u'EDIP2003', u'non-renewable resources', u'manganese'),
 # (u'EDIP2003', u'non-renewable resources', u'mercury'),
 # (u'EDIP2003', u'non-renewable resources', u'molybdenum'),
 # (u'EDIP2003', u'non-renewable resources', u'natural gas'),
 # (u'EDIP2003', u'non-renewable resources', u'nickel'),
 # (u'EDIP2003', u'non-renewable resources', u'oil'),
 # (u'EDIP2003', u'non-renewable resources', u'palladium'),
 # (u'EDIP2003', u'non-renewable resources', u'platinum'),
 # (u'EDIP2003', u'non-renewable resources', u'silver'),
 # (u'EDIP2003', u'non-renewable resources', u'tantalum'),
 # (u'EDIP2003', u'non-renewable resources', u'tin'),
 # (u'EDIP2003', u'non-renewable resources', u'zinc'),
 (u'EDIP2003', u'renewable resources', u'wood'),
 (u'EDIP2003', u'stratospheric ozone depletion', u'ODP total'),
 (u'EPS 2000', u'total', u'abiotic stock resources'),
 (u'EPS 2000', u'total', u'emissions into soil'),
 (u'EPS 2000', u'total', u'emissions into water'),
 (u'EPS 2000', u'total', u'land occupation'),
 # (u'IMPACT 2002+ (Endpoint)',
 #  u'ecosystem quality',
 #  u'Copy of land occupation'),
 (u'IMPACT 2002+ (Endpoint)', u'ecosystem quality', u'land occupation'),
 (u'IMPACT 2002+ (Endpoint)', u'human health', u'ozone layer depletion'),
 (u'IMPACT 2002+ (Endpoint)', u'resources', u'mineral extraction'),
 (u'IMPACT 2002+ (Endpoint)', u'resources', u'non-renewable energy'),
 # (u'IMPACT 2002+ (Endpoint)', u'resources', u'total'),
 (u'IMPACT 2002+ (Midpoint)', u'ecosystem quality', u'aquatic acidification'),
 (u'IPCC 2001', u'climate change', u'GWP 100a'),
 # (u'IPCC 2001', u'climate change', u'GWP 20a'),
 # (u'IPCC 2001', u'climate change', u'GWP 500a'),
 # (u'IPCC 2007', u'climate change', u'GWP 100a'),
 # (u'IPCC 2007', u'climate change', u'GWP 20a'),
 # (u'IPCC 2007', u'climate change', u'GWP 500a'),
 # (u'ReCiPe Endpoint (E,A)',
 #  u'ecosystem quality',
 #  u'agricultural land occupation'),
 # (u'ReCiPe Endpoint (E,A)',
 #  u'ecosystem quality',
 #  u'freshwater eutrophication'),
 # (u'ReCiPe Endpoint (E,A)',
 #  u'ecosystem quality',
 #  u'natural land transformation'),
 # (u'ReCiPe Endpoint (E,A)',
 #  u'ecosystem quality',
 #  u'terrestrial acidification'),
 # (u'ReCiPe Endpoint (E,A)', u'ecosystem quality', u'urban land occupation'),
 # (u'ReCiPe Endpoint (E,A)', u'resources', u'fossil depletion'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'agricultural land occupation'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'freshwater eutrophication'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'natural land transformation'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'terrestrial acidification'),
 (u'ReCiPe Endpoint (H,A)', u'ecosystem quality', u'urban land occupation'),
 (u'ReCiPe Endpoint (H,A)', u'human health', u'particulate matter formation'),
 (u'ReCiPe Endpoint (H,A)', u'resources', u'fossil depletion'),
 # (u'ReCiPe Endpoint (I,A)', u'resources', u'fossil depletion'),
 (u'TRACI', u'environmental impact', u'acidification'),
 (u'TRACI', u'environmental impact', u'eutrophication'),
 (u'TRACI', u'environmental impact', u'global warming'),
 (u'TRACI', u'environmental impact', u'ozone depletion'),
 (u'TRACI', u'human health', u'respiratory effects, average'),
 (u'cumulative energy demand', u'total'),
 # Add these together
 # (u'cumulative energy demand',
 #  u'biomass',
 #  u'renewable energy resources, biomass'),
 # (u'cumulative energy demand',
 #  u'fossil',
 #  u'non-renewable energy resources, fossil'),
 # (u'cumulative energy demand',
 #  u'geothermal',
 #  u'renewable energy resources, geothermal, converted'),
 # (u'cumulative energy demand',
 #  u'nuclear',
 #  u'non-renewable energy resources, nuclear'),
 # (u'cumulative energy demand',
 #  u'primary forest',
 #  u'non-renewable energy resources, primary forest'),
 # (u'cumulative energy demand',
 #  u'solar',
 #  u'renewable energy resources, solar, converted'),
 # (u'cumulative energy demand',
 #  u'water',
 #  u'renewable energy resources, potential (in barrage water), converted'),
 # (u'cumulative energy demand',
 #  u'wind',
 #  u'renewable energy resources, kinetic (in wind), converted'),
 (u'cumulative exergy demand',  u'total'),
 # Add these together
 # (u'cumulative exergy demand',
 #  u'biomass',
 #  u'renewable energy resources, biomass'),
 # (u'cumulative exergy demand',
 #  u'fossil',
 #  u'non-renewable energy resources, fossil'),
 # (u'cumulative exergy demand',
 #  u'metals',
 #  u'non-renewable material resources, metals'),
 # (u'cumulative exergy demand',
 #  u'minerals',
 #  u'non-renewable material resources, minerals'),
 # (u'cumulative exergy demand',
 #  u'nuclear',
 #  u'non-renewable energy resources, nuclear'),
 # (u'cumulative exergy demand',
 #  u'primary forest',
 #  u'non-renewable energy resources, primary forest'),
 # (u'cumulative exergy demand',
 #  u'solar',
 #  u'renewable energy resources, solar, converted'),
 # (u'cumulative exergy demand',
 #  u'water',
 #  u'renewable energy resources, potential (in barrage water), converted'),
 # (u'cumulative exergy demand',
 #  u'water resources',
 #  u'renewable material resources, water'),
 # (u'cumulative exergy demand',
 #  u'wind',
 #  u'renewable energy resources, kinetic (in wind), converted'),
 (u'eco-indicator 99, (H,A)',
  u'ecosystem quality',
  u'acidification & eutrophication'),
 (u'eco-indicator 99, (H,A)', u'ecosystem quality', u'ecotoxicity'),
 (u'eco-indicator 99, (H,A)', u'ecosystem quality', u'land occupation'),
 # (u'eco-indicator 99, (H,A)', u'ecosystem quality', u'total'),
 (u'eco-indicator 99, (H,A)', u'human health', u'carcinogenics'),
 (u'eco-indicator 99, (H,A)', u'human health', u'climate change'),
 (u'eco-indicator 99, (H,A)', u'human health', u'ozone layer depletion'),
 (u'eco-indicator 99, (H,A)', u'resources', u'fossil fuels'),
 (u'eco-indicator 99, (H,A)', u'resources', u'mineral extraction'),
 # (u'eco-indicator 99, (H,A)', u'resources', u'total'),
 # (u'eco-indicator 99, (H,A) w/o LT',
 #  u'ecosystem quality w/o LT',
 #  u'acidification & eutrophication w/o LT'),
 # (u'eco-indicator 99, (H,A) w/o LT',
 #  u'ecosystem quality w/o LT',
 #  u'land occupation w/o LT'),
 # (u'eco-indicator 99, (H,A) w/o LT',
 #  u'human health w/o LT',
 #  u'carcinogenics w/o LT'),
 # (u'eco-indicator 99, (H,A) w/o LT',
 #  u'human health w/o LT',
 #  u'climate change w/o LT'),
 # (u'eco-indicator 99, (H,A) w/o LT',
 #  u'human health w/o LT',
 #  u'ozone layer depletion w/o LT'),
 # (u'eco-indicator 99, (H,A) w/o LT',
 #  u'resources w/o LT',
 #  u'fossil fuels w/o LT'),
 # (u'eco-indicator 99, (H,A) w/o LT',
 #  u'resources w/o LT',
 #  u'mineral extraction w/o LT'),
 # (u'eco-indicator 99, (H,A) w/o LT', u'resources w/o LT', u'total w/o LT'),
 (u'ecological footprint', u'total', u'CO2'),
 (u'ecological footprint', u'total', u'land occupation'),
 (u'ecological footprint', u'total', u'nuclear'),
 # (u'ecological footprint', u'total', u'total'),
 (u'ecological scarcity 2006', u'total', u'deposited waste'),
 (u'ecological scarcity 2006', u'total', u'emission into groundwater'),
 (u'ecological scarcity 2006', u'total', u'energy resources'),
 (u'ecological scarcity 2006', u'total', u'natural resources'),
 (u'ecosystem damage potential', u'total', u'linear, land occupation'),
 (u'ecosystem damage potential', u'total', u'linear, land transformation'),
 # (u'ecosystem damage potential', u'total', u'linear, land use, total')
]
