CANDIDATES = [
 (u'CML 2001', u'acidification potential', u'average European'),
 (u'CML 2001', u'climate change', u'GWP 100a'),
 (u'CML 2001', u'eutrophication potential', u'average European'),
 (u'CML 2001', u'freshwater aquatic ecotoxicity', u'FAETP 100a'),
 (u'CML 2001', u'human toxicity', u'HTP 100a'),
 (u'CML 2001', u'land use', u'competition'),
 (u'CML 2001', u'marine aquatic ecotoxicity', u'MAETP infinite'),
 (u'CML 2001', u'resources', u'depletion of abiotic resources'),
 (u'CML 2001', u'stratospheric ozone depletion', u'ODP 25a'),
 (u'EDIP2003', u'ecotoxicity', u'in sewage treatment plants'),
 (u'EDIP2003', u'eutrophication', u'terrestrial eutrophication'),
 (u'EDIP2003', u'renewable resources', u'wood'),
 (u'EDIP2003', u'stratospheric ozone depletion', u'ODP total'),
 (u'EPS 2000', u'total', u'abiotic stock resources'),
 (u'EPS 2000', u'total', u'emissions into soil'),
 (u'EPS 2000', u'total', u'emissions into water'),
 (u'EPS 2000', u'total', u'land occupation'),
 (u'IMPACT 2002+ (Endpoint)', u'ecosystem quality', u'land occupation'),
 (u'IMPACT 2002+ (Endpoint)', u'human health', u'ozone layer depletion'),
 (u'IMPACT 2002+ (Endpoint)', u'resources', u'mineral extraction'),
 (u'IMPACT 2002+ (Endpoint)', u'resources', u'non-renewable energy'),
 (u'IMPACT 2002+ (Midpoint)', u'ecosystem quality', u'aquatic acidification'),
 (u'IPCC 2001', u'climate change', u'GWP 100a'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'agricultural land occupation'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'freshwater eutrophication'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'natural land transformation'),
 (u'ReCiPe Endpoint (H,A)',
  u'ecosystem quality',
  u'terrestrial acidification'),
 (u'ReCiPe Endpoint (H,A)', u'ecosystem quality', u'urban land occupation'),
 (u'ReCiPe Endpoint (H,A)', u'human health', u'particulate matter formation'),
 (u'ReCiPe Endpoint (H,A)', u'resources', u'fossil depletion'),
 (u'TRACI', u'environmental impact', u'acidification'),
 (u'TRACI', u'environmental impact', u'eutrophication'),
 (u'TRACI', u'environmental impact', u'global warming'),
 (u'TRACI', u'environmental impact', u'ozone depletion'),
 (u'TRACI', u'human health', u'respiratory effects, average'),
 (u'cumulative energy demand', u'total'),
 (u'cumulative exergy demand',  u'total'),
 (u'eco-indicator 99, (H,A)',
  u'ecosystem quality',
  u'acidification & eutrophication'),
 (u'eco-indicator 99, (H,A)', u'ecosystem quality', u'ecotoxicity'),
 (u'eco-indicator 99, (H,A)', u'ecosystem quality', u'land occupation'),
 (u'eco-indicator 99, (H,A)', u'human health', u'carcinogenics'),
 (u'eco-indicator 99, (H,A)', u'human health', u'climate change'),
 (u'eco-indicator 99, (H,A)', u'human health', u'ozone layer depletion'),
 (u'eco-indicator 99, (H,A)', u'resources', u'fossil fuels'),
 (u'eco-indicator 99, (H,A)', u'resources', u'mineral extraction'),
 (u'ecological footprint', u'total', u'CO2'),
 (u'ecological footprint', u'total', u'land occupation'),
 (u'ecological footprint', u'total', u'nuclear'),
 (u'ecological scarcity 2006', u'total', u'deposited waste'),
 (u'ecological scarcity 2006', u'total', u'emission into groundwater'),
 (u'ecological scarcity 2006', u'total', u'energy resources'),
 (u'ecological scarcity 2006', u'total', u'natural resources'),
 (u'ecosystem damage potential', u'total', u'linear, land occupation'),
 (u'ecosystem damage potential', u'total', u'linear, land transformation'),
]
